version: 0.2

phases:
  build:
    commands:
      - echo "Deploying frontend to S3..."
      - cd frontend
      - aws s3 sync . s3://photo-album-stack-frontend-bucket/ --delete --exclude "buildspec.yml"
      - echo "Frontend deployment complete"

artifacts:
  files:
    - '**/*'
  base-directory: frontend
