version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  
  build:
    commands:
      - echo "Packaging Lambda functions..."
      - cd backend/lambda/index-photos
      - zip -r ../../../index-photos.zip lambda_function.py
      - cd ../search-photos
      - zip -r ../../../search-photos.zip lambda_function.py
      - cd ../../..
  
  post_build:
    commands:
      - echo "Deploying Lambda functions..."
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://index-photos.zip
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://search-photos.zip
      - echo "Deployment complete"

artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
