AWSTemplateFormatVersion: '2010-09-09'
Description: 'Photo Album Search Application - CloudFormation Template'

Parameters:
  OpenSearchEndpoint:
    Type: String
    Description: OpenSearch domain endpoint
    Default: ''
  
  OpenSearchUsername:
    Type: String
    Description: OpenSearch master username
    Default: 'admin'
  
  OpenSearchPassword:
    Type: String
    Description: OpenSearch master password
    NoEcho: true
    Default: ''
  
  LexBotId:
    Type: String
    Description: Amazon Lex Bot ID
    Default: ''
  
  LexBotAliasId:
    Type: String
    Description: Amazon Lex Bot Alias ID
    Default: ''

Resources:
  # S3 Bucket B1 - Frontend
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-frontend-bucket'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3000

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${FrontendBucket}/*'

  # S3 Bucket B2 - Photos
  PhotosBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-photos-bucket'
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - PUT
              - POST
              - GET
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3000

  # IAM Role for Index Photos Lambda (LF1)
  IndexPhotosLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-index-photos-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: IndexPhotosPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:HeadObject
                Resource: !Sub 'arn:aws:s3:::${PhotosBucket}/*'
              - Effect: Allow
                Action:
                  - rekognition:DetectLabels
                Resource: '*'
              - Effect: Allow
                Action:
                  - es:ESHttpPost
                  - es:ESHttpPut
                Resource: '*'

  # IAM Role for Search Photos Lambda (LF2)
  SearchPhotosLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-search-photos-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonLexFullAccess
      Policies:
        - PolicyName: SearchPhotosPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - es:ESHttpPost
                  - es:ESHttpGet
                Resource: '*'

  # Lambda Function LF1 - Index Photos
  IndexPhotosLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: index-photos
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Role: !GetAtt IndexPhotosLambdaRole.Arn
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          OPENSEARCH_ENDPOINT: !Ref OpenSearchEndpoint
          OPENSEARCH_INDEX: photos
          OPENSEARCH_USERNAME: !Ref OpenSearchUsername
          OPENSEARCH_PASSWORD: !Ref OpenSearchPassword
      Code:
        ZipFile: |
          import json
          import boto3
          import os
          import urllib.request
          import base64
          from datetime import datetime
          import logging
          
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          
          s3_client = boto3.client('s3')
          rekognition_client = boto3.client('rekognition')
          
          OPENSEARCH_ENDPOINT = os.environ.get('OPENSEARCH_ENDPOINT')
          OPENSEARCH_INDEX = os.environ.get('OPENSEARCH_INDEX', 'photos')
          OPENSEARCH_USERNAME = os.environ.get('OPENSEARCH_USERNAME', 'admin')
          OPENSEARCH_PASSWORD = os.environ.get('OPENSEARCH_PASSWORD')
          
          def lambda_handler(event, context):
              try:
                  logger.info(f"Event: {json.dumps(event)}")
                  for record in event['Records']:
                      bucket = record['s3']['bucket']['name']
                      object_key = record['s3']['object']['key']
                      logger.info(f"Processing: {object_key} from {bucket}")
                      
                      rekognition_response = rekognition_client.detect_labels(
                          Image={'S3Object': {'Bucket': bucket, 'Name': object_key}},
                          MaxLabels=10, MinConfidence=50
                      )
                      rekognition_labels = [label['Name'].lower() for label in rekognition_response['Labels']]
                      
                      try:
                          metadata = s3_client.head_object(Bucket=bucket, Key=object_key)
                          custom_str = metadata.get('Metadata', {}).get('customlabels', '')
                          custom_labels = [l.strip().lower() for l in custom_str.split(',') if l.strip()]
                      except:
                          custom_labels = []
                      
                      all_labels = list(set(rekognition_labels + custom_labels))
                      document = {
                          "objectKey": object_key, "bucket": bucket,
                          "createdTimestamp": datetime.utcnow().isoformat(),
                          "labels": all_labels
                      }
                      
                      url = f"https://{OPENSEARCH_ENDPOINT}/{OPENSEARCH_INDEX}/_doc"
                      auth = base64.b64encode(f"{OPENSEARCH_USERNAME}:{OPENSEARCH_PASSWORD}".encode()).decode()
                      req = urllib.request.Request(url, data=json.dumps(document).encode(),
                          headers={"Content-Type": "application/json", "Authorization": f"Basic {auth}"}, method='POST')
                      with urllib.request.urlopen(req) as resp:
                          if resp.status in [200, 201]:
                              logger.info(f"Indexed: {object_key}")
                  return {'statusCode': 200, 'body': 'Success'}
              except Exception as e:
                  logger.error(f"Error: {str(e)}")
                  raise e

  # Lambda Function LF2 - Search Photos
  SearchPhotosLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: search-photos
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      Role: !GetAtt SearchPhotosLambdaRole.Arn
      Timeout: 10
      MemorySize: 256
      Environment:
        Variables:
          OPENSEARCH_ENDPOINT: !Ref OpenSearchEndpoint
          OPENSEARCH_INDEX: photos
          OPENSEARCH_USERNAME: !Ref OpenSearchUsername
          OPENSEARCH_PASSWORD: !Ref OpenSearchPassword
          LEX_BOT_ID: !Ref LexBotId
          LEX_BOT_ALIAS_ID: !Ref LexBotAliasId
      Code:
        ZipFile: |
          import json
          import boto3
          import os
          import urllib.request
          import base64
          import logging
          
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)
          
          lex_client = boto3.client('lexv2-runtime')
          OPENSEARCH_ENDPOINT = os.environ.get('OPENSEARCH_ENDPOINT')
          OPENSEARCH_INDEX = os.environ.get('OPENSEARCH_INDEX', 'photos')
          OPENSEARCH_USERNAME = os.environ.get('OPENSEARCH_USERNAME')
          OPENSEARCH_PASSWORD = os.environ.get('OPENSEARCH_PASSWORD')
          LEX_BOT_ID = os.environ.get('LEX_BOT_ID')
          LEX_BOT_ALIAS_ID = os.environ.get('LEX_BOT_ALIAS_ID')
          
          def normalize(kw):
              kw = kw.lower().strip()
              if kw.endswith('ies'): return kw[:-3] + 'y'
              if kw.endswith('es') and len(kw) > 3: return kw[:-2]
              if kw.endswith('s') and len(kw) > 2: return kw[:-1]
              return kw
          
          def extract_keywords(query):
              try:
                  if LEX_BOT_ID and LEX_BOT_ALIAS_ID:
                      resp = lex_client.recognize_text(botId=LEX_BOT_ID, botAliasId=LEX_BOT_ALIAS_ID,
                          localeId='en_US', sessionId='search', text=query)
                      keywords = []
                      if resp.get('interpretations'):
                          slots = resp['interpretations'][0].get('intent', {}).get('slots', {})
                          for s in slots.values():
                              if s and s.get('value'): keywords.append(s['value']['originalValue'].lower())
                      if keywords: return [normalize(k) for k in keywords]
                  return [normalize(w) for w in query.split() if len(w) > 2]
              except: return [normalize(query)]
          
          def search(keywords):
              should = [{"match": {"labels": k}} for k in keywords]
              should += [{"wildcard": {"labels": f"{k}*"}} for k in keywords]
              query = {"query": {"bool": {"should": should, "minimum_should_match": 1}}}
              url = f"https://{OPENSEARCH_ENDPOINT}/{OPENSEARCH_INDEX}/_search"
              auth = base64.b64encode(f"{OPENSEARCH_USERNAME}:{OPENSEARCH_PASSWORD}".encode()).decode()
              req = urllib.request.Request(url, data=json.dumps(query).encode(),
                  headers={"Content-Type": "application/json", "Authorization": f"Basic {auth}"}, method='POST')
              with urllib.request.urlopen(req) as resp:
                  data = json.loads(resp.read())
                  return [h['_source'] for h in data.get('hits', {}).get('hits', [])]
          
          def lambda_handler(event, context):
              q = (event.get('queryStringParameters') or {}).get('q', '')
              if not q: return {'statusCode': 200, 'headers': {'Access-Control-Allow-Origin': '*'}, 'body': '[]'}
              keywords = extract_keywords(q)
              results = search(keywords) if keywords else []
              return {'statusCode': 200, 'headers': {'Content-Type': 'application/json',
                  'Access-Control-Allow-Origin': '*'}, 'body': json.dumps(results)}

  # Permission for S3 to invoke Index Photos Lambda
  IndexPhotosLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IndexPhotosLambda
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub 'arn:aws:s3:::${PhotosBucket}'

  # API Gateway
  PhotoAlbumAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub '${AWS::StackName}-api'
      Description: Photo Album Search API

  PhotosResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref PhotoAlbumAPI
      ParentId: !GetAtt PhotoAlbumAPI.RootResourceId
      PathPart: photos

  SearchResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref PhotoAlbumAPI
      ParentId: !GetAtt PhotoAlbumAPI.RootResourceId
      PathPart: search

  PhotosKeyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref PhotoAlbumAPI
      ParentId: !Ref PhotosResource
      PathPart: '{key}'

  # PUT /photos/{key} - S3 Proxy
  PhotosPutMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref PhotoAlbumAPI
      ResourceId: !Ref PhotosKeyResource
      HttpMethod: PUT
      AuthorizationType: NONE
      ApiKeyRequired: true
      RequestParameters:
        method.request.path.key: true
        method.request.header.x-amz-meta-customlabels: false
        method.request.header.Content-Type: false
      Integration:
        Type: AWS
        IntegrationHttpMethod: PUT
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:s3:path/${PhotosBucket}/{key}'
        Credentials: !GetAtt ApiGatewayRole.Arn
        RequestParameters:
          integration.request.path.key: method.request.path.key
          integration.request.header.x-amz-meta-customlabels: method.request.header.x-amz-meta-customlabels
          integration.request.header.Content-Type: method.request.header.Content-Type
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        PassthroughBehavior: WHEN_NO_MATCH
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true

  # GET /search
  SearchGetMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref PhotoAlbumAPI
      ResourceId: !Ref SearchResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      RequestParameters:
        method.request.querystring.q: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SearchPhotosLambda.Arn}/invocations'

  # IAM Role for API Gateway S3 Access
  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: !Sub 'arn:aws:s3:::${PhotosBucket}/*'

  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub '${AWS::StackName}-api-key'
      Enabled: true

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: ApiDeployment
    Properties:
      UsagePlanName: !Sub '${AWS::StackName}-usage-plan'
      ApiStages:
        - ApiId: !Ref PhotoAlbumAPI
          Stage: prod

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - PhotosPutMethod
      - SearchGetMethod
    Properties:
      RestApiId: !Ref PhotoAlbumAPI
      StageName: prod

  SearchPhotosLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SearchPhotosLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${PhotoAlbumAPI}/*/*'

Outputs:
  FrontendWebsiteURL:
    Description: Frontend website URL
    Value: !Sub 'http://${FrontendBucket}.s3-website-${AWS::Region}.amazonaws.com'

  PhotosBucketName:
    Description: Photos S3 bucket name
    Value: !Ref PhotosBucket

  ApiGatewayURL:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${PhotoAlbumAPI}.execute-api.${AWS::Region}.amazonaws.com/prod'

  ApiKeyId:
    Description: API Key ID
    Value: !Ref ApiKey
